### ISSUE TITLE
Data Source Sharing!

### ISSUE THREAD

**Issue by tommyngx** [ReasonJ01/Knee-Arthritis-Diagnosis-Tool#1]
Hi, could you please share the data source of your project? Is it from OAI dataset? could you please share it to me! I am do appreciate it! I can't download OAI from NIH website and wait for 2 months for the approval! Thank you for your sharing!

**Comment by ReasonJ01** [comment]
Hi, I have just added a link to the readme and here it is again: https://data.mendeley.com/datasets/56rmx5bjcr/1
